plugins {
    id 'java-library'
    id 'eclipse'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
        vendor = JvmVendorSpec.ADOPTIUM
    }
}
tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

dependencies {
    api            'com.github.SoltauFintel.amalia:amalia-web:3.0.0-a3'
    api            'com.github.SoltauFintel.amalia:amalia-git:3.0.0-a3'
    api            'commons-io:commons-io:2.12.0'
    implementation 'org.gitlab4j:gitlab4j-api:5.0.1' // keep this version
	implementation 'io.opentelemetry:opentelemetry-api:1.54.1'
	implementation 'com.github.ben-manes.caffeine:caffeine:3.2.3'
    implementation 'io.valkey:valkey-java:5.5.0'
    implementation 'de.mwvb:xmldocument:0.2.4'
}

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
    maven { url 'https://www.javaxt.com/maven' }
}
