subpages=Untergeordnete Seiten
reorder=Umordnen
sort=Sortieren
edit=Bearbeiten
newPage=Neue Seite
pullT=Seite erneut vom Server laden
none=keine
move=Verschieben
delete=Löschen
language=Sprache
alfaSorted=Sortierung: alphabetisch sortiert
manuSorted=Sortierung: manuell sortiert
sortConfirm=Hiermit speichern Sie eine alphabetische Sortierung der direkten Unterseiten!
pageToPrev=zurückblättern
pageToNext=weiterblättern
newBook=Neues Buch
title=Titel
ordner=Ordner
books=Bücher
pullWS=Workspace aktualisieren
cloneWS=Workspace komplett neu laden
tagCloud=tag cloud
orderByName=nach Namen sortiert
orderBySize=nach Häufigkeit sortiert
selectWS=Bitte wählen Sie einen Workspace. Erstellen Sie sich einen neuen Workspace, falls der gewünschte Branch nicht angezeigt wird.
persistence=Persistenz
createWS=Neuen Workspace erstellen
save=Speichern
cancel=Abbruch
deletePage1=Hiermit löschen Sie die Seite
deletePage2=Es wird die Seite in allen Sprachen und mit allen enthaltenen Bildern gelöscht. Ebenso werden alle Unterseiten gelöscht.
deletePage=Seite löschen
keepPage=Seite behalten
addBook=Neues Buch anlegen
buchtitel=Buchtitel
editBook=Buch bearbeiten
deleteBook=Buch löschen
deleteBook1=Hiermit löschen Sie den Bucheintrag
deleteBook2=Der Buchordner wird nicht gelöscht und muss ggf. im Speichersystem manuell gelöscht werden.
keepBook=Buch behalten
reorderSubpages=Unterseiten ordnen
reorder1=Bitte die Unterseiten per Drag & Drop umordnen:
fertigSpeichern=Fertig, speichern!
linkResolver1=Seite <b>$t</b> wählen und weiter...
linkResolver0=Link unverändert lassen und weiter...
message=Meldung
goToHomepage=Zur Startseite
pageNotFound=Seite nicht vorhanden!
pageNotFound2=Die gesuchte Seite ist leider nicht verfügbar. Möglicherweise liegen die gesuchten Informationen inzwischen an einem anderen Ort oder die Seite existiert nicht mehr. Starten Sie erneut von der Startseite aus.
error.enterFolder=Bitte Ordnernamen eingeben!
error.folderAlreadyExists=Buchordner bereits vorhanden!
error.enterTitle=Bitte Titel eingeben!
error.simultaneousEditing=Gleichzeitige Bearbeitung erkannt! Bitte zurück gehen, die Änderungen anderweitig speichern, Seite neu laden und Bearbeitung erneut versuchen.
error.imageTooBig=Bitte verwenden Sie eine Grafik, die nicht größer als 10 MB ist!
createWS1=Bereits erstellte Workspaces und Minerva-interne Branches werden in der Liste nicht aufgeführt.
deleteWS=Workspace löschen
deleteWS1=Hiermit löschen Sie den Workspace
deleteWS2=Der Branch wird nicht im Gitlab Repository gelöscht.
deleteWS3=Workspace "master" darf nicht gelöscht werden!
deleteWS4=Der letzte Workspace darf nicht gelöscht werden!
keepWS=Workspace behalten
note=Kommentar
addNote=Neuen Kommentar schreiben
editNote=Kommentar bearbeiten
viewNote=Kommentar anzeigen
notes=Kommentare
backToPage=Zurück zur Seite
reply=Antworten
deleteQ=Hiermit löschen Sie diesen Kommentar.
movePage=Seite verschieben
movePage1=Die Seite "$t" erhält die Seite "$p" als neue übergeordnete Seite.
movePage2=Die Seite "$t" wird in das Buch "$b" verschoben.
deletePage=Seite löschen
logout=Abmelden
noBranches=Es wurde bereits für jeden Branch ein Workspace angelegt.
currentParentPage=aktuelle übergeordnete Seite
deleteAllTags=Alle tags löschen
newTag=Neues tag
anzahl=Anzahl
page=Seite
book=Buch
allNotes=Alle Kommentare
author=Autor
authors=Autoren
createdAt=Erstellt am
preview=Vorschau
otherBook=anderes Buch
reindex=Suchindex aktualisieren
searchPlaceholder=Volltextsuche
volltextsuche=Volltextsuche
treffer=Treffer
reindex-complete=Der Suchindex wurde für alle Bücher aktualisiert.
viewBook=Buch im Bearbeitungsbereich anzeigen
viewPage=Seite im Bearbeitungsbereich anzeigen
hasNote=Kommentar(e) vorhanden
exclusions=Ausschlüsse
noSpecificCustomer=kein Kunde
addMoreTags=Weitere tags hinzufügen
noTags=keine tags vorhanden
noNotes=keine Kommentare vorhanden
allPages=Alle Seiten anzeigen
done=Erledigt
doneNote=Kommentar als erledigt kennzeichnen
undoneNote=Kommentar als unerledigt kennzeichnen
zustaendig=zuständig
doneBy=erledigt durch
myTasks=Meine Aufgaben
history=Historie
date=Datum
newTag=Neues tag
historyFor=Git Historie für Datei
editTags=tags bearbeiten
whatChanged=Was haben Sie geändert?
lastChangeInfo=letzte Änderung am $d durch $u$c
lastChangeInfoForBook=letzte Änderung von Seite "$p" am $d durch $u$c
pageLinkToThisPage=Diese Seite verlinkt auf die zu löschende Seite. Es wird empfohlen erst die Links zu korrigieren, damit keine Broken Links entstehen.
pagesLinkToThisPage=Diese Seiten verlinken auf die zu löschende Seite. Es wird empfohlen erst die Links zu korrigieren, damit keine Broken Links entstehen.
helpKeys=Hilfe-Keys
allHelpKeys=Alle Hilfe-Keys
updateOnlineHelp=Online-Hilfe aktualisieren
session-expired=Session ist abgelaufen. Bitte erneut anmelden.
customerMapping=Mapping
force=Anzeige erzwingen
mapping1=Vorhandene Verknüpfungen
mapping2=Verknüpfung hinzufügen
favorite=Favorit
linkAnalysis=Link-Analyse
type=Typ
linkTitle=Link-Titel
pageTitle=Seitentitel
formulaEditor=Formeleingabe
formula=Formel
giveAdminRights=Admin-Rechte erhalten
dropAdminRights=Admin-Rechte aufgeben
serverlog=Serverlog
createBranch=Branch erstellen
branchName=Branch-Name
validBranchName=Bitte geben Sie einen gültigen Branchnamen ein!
createBranchM=Hiermit erstellen Sie einen neuen Branch und Workspace auf Basis des letzten Commits von Branch $m.
mergeBranch=Branch mergen
noBranches=Es gibt keine Branches.
sourceBranch=Quell-Branch
mergeInfo=Welchen Branch in den Branch $t mergen?
Branch=Branch
mergen=Mergen
noLinks=keine Links
export=Export
exportWhat=Was exportieren
customer=Kunde
allBooks=alle Bücher
exportInfo=Bücher bzw. Seiten werden als mehrseitige HTML-Dateien exportiert und als Zip-Datei heruntergeladen.
booksModeTitle=Bücherübersicht
back=zurück
forward=weiter
exportTemplates=Exportvorlagen
booksOverview=Bücher Übersicht
template=Template
Menu=Menü
watchPage=Seite beobachten
watchSubpages=Unterseiten beobachten
notExistingBranch=Der Branch existiert nicht mehr im Gitlab Repository. Bitte lösche den Workspace.
workspaceNotOk=Workspace "$b" ist nicht in Ordnung!
ctrlS=Strg+S
workspaceHistory=Alle Änderungen
noMoreCommits=keine weiteren Commits
locked.header=Seite gesperrt
locked.info=Die Seite "$t" wird derzeit von $u bearbeitet.
locked.time=Sperre bis $o Uhr
locked.edit=Seite trotzdem bearbeiten
locked.no-edit=OK, nicht bearbeiten
brokenMappingsInfo=Es gibt keine Broken Mappings.
close=Schließen
TOC=TOC
standard=Standard
withSubpages=mit Unterseiten
off=aus
tocHeadingsLevels=Überschriften-Ebenen
tocSubpagesLevels=Unterseiten-Ebenen
cantDeleteAllFiles=Es konnten nicht alle Dateien gelöscht werden!\nBitte an Administrator wenden. ID $id
editorsNote=Bearbeitungshinweis
clickToRemove=Hinweis ausblenden
mergeRequestCantBeMerged=Merge Request <a href="$url" target="_blank">$id</a> kann nicht gemerget werden. Bitte <a href="$url/conflicts" target="_blank">lösen Sie die Konflikte</a> in Gitlab, committen diese und mergen den Merge Request. Danach <a href="/w/$tb/pull">aktualisieren</a> Sie bitte den Minerva-Workspace.
