subpages=Unterseiten
reorder=Umordnen
sort=Sortieren
edit=Bearbeiten
newPage=Neue Seite
newFeature=Neues Feature
pullT=Seite erneut vom Server laden
none=keine
move=Verschieben
delete=Löschen
language=Sprache
alfaSorted=Sortierung: alphabetisch sortiert
manuSorted=Sortierung: manuell sortiert
sortConfirm=Hiermit speichern Sie eine alphabetische Sortierung der direkten Unterseiten!
pageToPrev=zurückblättern
pageToNext=weiterblättern
newBook=Neues Buch
title=Titel
ordner=Ordner
books=Bücher
pullWS=Workspace aktualisieren
cloneWS=Workspace komplett neu laden
tagCloud=tag cloud
orderByName=nach Namen sortiert
orderBySize=nach Häufigkeit sortiert
selectWS=Bitte wählen Sie einen Workspace. Erstellen Sie sich einen neuen Workspace, falls der gewünschte Branch nicht angezeigt wird.
persistence=Persistenz
createWS=Neuen Workspace erstellen
save=Speichern
cancel=Abbruch
deletePage1=Hiermit löschen Sie die Seite
deletePage2=Es wird die Seite in allen Sprachen und mit allen enthaltenen Bildern gelöscht. Ebenso werden alle Unterseiten, Attachments und Kommentare gelöscht.
deletePage3=Die Löschaktion kann über den Papierkorb rückgängig gemacht werden.
deletePage=Seite löschen
keepPage=Seite behalten
addBook=Neues Buch anlegen
buchtitel=Buchtitel
editBook=Buch bearbeiten
deleteBook=Buch löschen
deleteBook1=Hiermit löschen Sie den Bucheintrag
deleteBook2=Der Buchordner wird nicht gelöscht und muss ggf. im Speichersystem manuell gelöscht werden.
keepBook=Buch behalten
reorderSubpages=Unterseiten ordnen
reorder1=Bitte die Unterseiten per Drag & Drop umordnen:
fertigSpeichern=Fertig, speichern!
linkResolver1=Seite <b>$t</b> wählen und weiter...
linkResolver0=Link unverändert lassen und weiter...
message=Meldung
goToHomepage=Zur Startseite
pageNotFound=Seite nicht vorhanden!
pageNotFound2=Die gesuchte Seite ist leider nicht verfügbar. Möglicherweise liegen die gesuchten Informationen inzwischen an einem anderen Ort oder die Seite existiert nicht mehr. Starten Sie erneut von der Startseite aus.
pageNotFound3=Feature oder Seite mit ID "$id" nicht vorhanden!
linkMustStartWithHttp=Link muss mit http:// oder https:// beginnen!
error.enterFolder=Bitte Ordnernamen eingeben!
error.folderAlreadyExists=Buchordner bereits vorhanden!
error.enterTitle=Bitte Titel eingeben!
error.simultaneousEditing=Gleichzeitige Bearbeitung erkannt!
error.imageTooBig=Bitte verwenden Sie eine Grafik, die nicht größer als 10 MB ist!
createWS1=Bereits erstellte Workspaces und Minerva-interne Branches werden in der Liste nicht aufgeführt.
deleteWS=Workspace löschen
deleteWS1=Hiermit löschen Sie den Workspace
deleteWS2=Der Branch wird nicht im Gitlab Repository gelöscht.
deleteWS3=Workspace "master" darf nicht gelöscht werden!
deleteWS4=Der letzte Workspace darf nicht gelöscht werden!
keepWS=Workspace behalten
Comment=Kommentar
addComment=Neuen Kommentar schreiben
editComment=Kommentar bearbeiten
answerComment=Auf Kommentar antworten
comment-by=Kommentar von
viewTask=$t anzeigen
comments=Kommentare
backToPage=Zurück zur Seite
reply=Antworten
deleteQ=Hiermit löschen Sie diesen Kommentar.
movePage=Seite verschieben
movePage1=Die Seite "$t" erhält die Seite "$p" als neue übergeordnete Seite.
movePage2=Die Seite "$t" wird in das Buch "$b" verschoben.
logout=Abmelden
noBranches=Es wurde bereits für jeden Branch ein Workspace angelegt.
currentParentPage=aktuelle übergeordnete Seite
ParentPage=Übergeordnete Seite
deleteAllTags=Alle tags löschen
newTag=Neues tag
anzahl=Anzahl
page=Seite
book=Buch
author=Autor
authors=Autoren
createdAt=Erstellt am
preview=Vorschau
otherBook=anderes Buch
reindex=Suchindex aktualisieren
searchPlaceholder=Volltextsuche
volltextsuche=Volltextsuche
treffer=Treffer
reindex-complete=Der Suchindex wurde für alle Bücher aktualisiert.
viewBook=Buch im Bearbeitungsbereich anzeigen
viewPage=Seite im Bearbeitungsbereich anzeigen
hasText=Text vorhanden
hasComment=Kommentar(e) vorhanden
exclusions=Ausschlüsse
noSpecificCustomer=kein Kunde
addMoreTags=Weitere tags hinzufügen
noTags=keine tags vorhanden
noComments=keine Kommentare vorhanden
allPages=alle Seiten anzeigen
allPagesOff=Alle Seiten anzeigen AUS
done=Erledigt
doneComment=Kommentar als erledigt kennzeichnen
undoneComment=Kommentar als unerledigt kennzeichnen
zustaendig=zuständig
doneBy=erledigt
myTasks=Meine Aufgaben
Tasks=Aufgaben
history=Historie
date=Datum
historyFor=Git Historie für Datei
editTags=tags bearbeiten
whatChanged=Was haben Sie geändert?
whatChangedTooltip=Schreiben Sie durch Kommas getrennte tags und stellen Sie ihnen das Präfix 'tag=' voran, um tags zu erstellen (anstelle des Änderungskommentars).
lastChangeInfo=letzte Änderung am $d durch $u$c
lastChangeInfoForBook=letzte Änderung von Seite "<a href="$h">$p</a>" am $d durch $u$c
pageLinkToThisPage=Die unten stehende Seite verlinkt auf die zu löschende Seite (oder Unterseite(n)). Es wird empfohlen erst die Links zu korrigieren, damit keine Broken Links entstehen.
pagesLinkToThisPage=Die unten stehenden Seiten verlinken auf die zu löschende Seite (oder Unterseite(n)). Es wird empfohlen erst die Links zu korrigieren, damit keine Broken Links entstehen.
helpKeys=Hilfe-Keys
allHelpKeys=Alle Hilfe-Keys
updateOnlineHelp=Online-Hilfe aktualisieren
session-expired=Session ist abgelaufen. Bitte erneut anmelden.
customerMapping=Mapping
force=Anzeige erzwingen
mapping1=Vorhandene Verknüpfungen
mapping2=Verknüpfung hinzufügen
favorite=Favorit
Favorites=Seitenfavoriten
linkAnalysis=Link-Analyse
type=Typ
linkTitle=Link-Titel
pageTitle=Seitentitel
formulaEditor=Formeleingabe
formula=Formel
giveAdminRights=Admin-Rechte erhalten
dropAdminRights=Admin-Rechte aufgeben
serverlog=Serverlog
createBranch=Branch erstellen
branchName=Branch-Name
validBranchName=Bitte geben Sie einen gültigen Branchnamen ein!
createBranchM=Hiermit erstellen Sie einen neuen Branch und Workspace auf Basis des letzten Commits von Branch $m.
mergeBranch=Branch mergen
noBranchForMerge=Es gibt keine Branches.
noBranchToAdd=Es gibt keinen Branch zum Hinzufügen.
sourceBranch=Quell-Branch
mergeInfo=Welchen Branch in den Branch $t mergen?
Branch=Branch
mergen=Mergen
noLinks=keine Links
export=Export
exportWhat=Was exportieren
customer=Kunde
allBooks=alle Bücher
booksModeTitle=Bücherübersicht
back=zurück
forward=weiter
Forward=Weiter
exportTemplates=Exportvorlagen
booksOverview=Bücher Übersicht
template=Template
Menu=Menü
watchPage=Seite beobachten
watchSubpages=Unterseiten beobachten
notExistingBranch=Der Branch existiert nicht mehr im Gitlab Repository. Bitte lösche den Workspace.
workspaceNotOk=Workspace "$b" ist nicht in Ordnung!
ctrlS=Strg+S
workspaceHistory=Alle Änderungen
noMoreCommits=keine weiteren Commits
locked.header=Seite gesperrt
locked.info1=Die Seite "$t" wird derzeit von $u bearbeitet.
locked.info2=Die Seite "$t" wird derzeit von $u bearbeitet. Die Bearbeitungssitzung des Benutzers $u wird abgebrochen. Alle vom Benutzer $u vorgenommenen Änderungen gehen verloren!
locked.smallinfo1=Sperre bis $o Uhr
locked.edit1=Offene Sitzung trotzdem abbrechen
locked.edit2=Trotzdem weiter
locked.no-edit=OK, nicht bearbeiten
locked.info1.self=Die Seite "$t" wird bereits von Ihnen bearbeitet!?
locked.smallinfo1.self=Sie können diese Sperre zukünftig vermeiden, indem Sie die Bearbeitung mit "Abbruch" abbrechen. Sperre bis $o Uhr
locked.edit1.self=Seite trotzdem bearbeiten
brokenMappingsInfo=Es gibt keine Broken Mappings.
close=Schließen
TOC=Inhaltsverzeichnis
standard=Standard
withSubpages=mit Unterseiten
off=aus
tocHeadingsLevels=Überschriften-Ebenen
tocSubpagesLevels=Unterseiten-Ebenen
cantDeleteAllFiles=Es konnten nicht alle Dateien gelöscht werden!\nBitte an Administrator wenden. ID $id
editorsNote=Bearbeitungshinweis
clickToRemove=Hinweis ausblenden
mergeRequestCantBeMerged=Merge Request <a href="$url" target="_blank">$id</a> kann nicht gemerget werden. Bitte <a href="$url/conflicts" target="_blank">lösen Sie die Konflikte</a> in Gitlab, committen diese und mergen den Merge Request. Danach <a href="/w/$tb/pull">aktualisieren</a> Sie bitte den Minerva-Workspace.
user=Benutzer
moveToBookInfo=Bitte beachte, dass die Links beim Verschieben in ein anderes Buch nicht mehr funktionieren werden.

v._ok=OK. Keine Fehler.
v._emptyHTML=Seite ist leer.
v.noBody=Seite hat kein body tag.
v.illegalHeading=Überschrift ist für diese Ebene nicht erlaubt. $0
v.firstHeadingMustBe1=Seite muss mit Überschrift 1 beginnen.
v.headingGap=Es gibt eine Überschriften Lücke zwischen $0 und $1.
v.emptyLinesAtBegin=Es gibt $0 Leerzeilen am Anfang.
v.emptyLinesAtBegin1=Es gibt $0 Leerzeile am Anfang.
v.emptyLinesAtEnd=Es gibt $0 Leerzeilen am Ende. 
v.emptyLinesAtEnd1=Es gibt $0 Leerzeile am Ende. 
v.doubleEmptyLines=Es gibt $0 Doppel-Leerzeilen.
v.doubleEmptyLines1=Es gibt $0 Doppel-Leerzeile.
v.illegalTagsInHeading=Überschrift darf keine weitere Formatierung enthalten: $0
v.missingImageFile=Grafikdatei fehlt: $0
v.httpImage=Grafikdatei bestehend aus http(s) URL: $0
v.brokenLocalAnchor=Der lokale Anker-Link "$1" verweist auf die nicht vorhandene Überschrift "$0".
unusedImages=Ungenutzte Grafikdateien
validate=Prüfe Seiten
nMessages=Anzahl Fehler
nPages=Anzahl Seiten mit Fehlern
openComment=unerledigter Kommentar
openComments=unerledigte Kommentare
commitMessage=Commit Message
beginFSMode=Verzögerte Persistierung einschalten
endFSMode=Verzögerte Persistierung ausschalten (Speichern)
endFSModeInfo=Hiermit schalten Sie die verzögerte Persistierung aus. Sollen all Ihre Änderungen persistiert oder verworfen werden?
persist=Speichern
cancelFSMode=Verwerfen
moveNotAllowedForFSMode=Bitte verschieben Sie keine Seite wenn die verzögerte Persistierung aktiv ist.
Release=Release
Import=Importieren
alleNochNichtVorhandenen=alle noch nicht vorhandenen
pageDoesntExist=Seite mit Titel "$t" existiert nicht!
generalChanges=Allgemeine Änderungen
mailAddress=Emailadresse
exportAllowed=Export-Recht
yes=ja
manageUsers=Benutzerverwaltung
editUser=Benutzer bearbeiten
addUser=Neuen Benutzer anlegen
createUser=Neuer Benutzer
deleteUser=Benutzer löschen
deleteUserX=Benutzer $user löschen?
multiPageHtml=Mehrseitiges HTML
exportFormat=Exportformat
goToMenu=Weiter zum Menü
downloadExportInfo=Der Export wurde erstellt und kann jetzt heruntergeladen werden:
downloadExportInfo2=Der Export wurde erstellt und kann jetzt angezeigt werden:
export-already-downloaded=Die Datei wurde bereits heruntergeladen und ist nicht mehr vorhanden. Bitte ggf. Export erneut ausführen.
addExportTemplateSet=Export Template Set erstellen
editExportTemplateSet=Export Template Set bearbeiten
deleteExportTemplateSet=Export Template Set löschen
no-export-template-sets=Export nicht möglich, da keine Export Template Sets vorhanden sind!
copy=Kopie
copyExportTemplateSet=Export Template Set duplizieren
pdfToc=Deckblatt und Inhaltsverz.
anotherExport=Weiteren Export ausführen
moreCommands=Weitere Befehle
withCover=mit Deckblatt
withTOC=mit Inhaltsverzeichnis
withChapters=mit Kapitelnumerierung
exportInfo=Bei Auswahl von "alle Bücher" werden Featurebaum und interne Bücher nicht einbezogen. Bei Auswahl von Kunde "-" werden keine tags berücksichtigt, d.h. es werden <i>alle</i> Seiten exportiert.
selectPage=Seite(n) auswählen
selectPageWithFeatures=Seite(n) auswählen (inkl. Features)
seitenauswahl=Export: Seitenauswahl
pages=Seiten
doExport=Exportieren
selectPageError=Bitte wählen Sie eine Seite!
createBookInfo=Bitte erstellen Sie ein Buch.
exportPage=Seite exportieren
loggedOut=Erfolgreich abgemeldet.
relogin=Wieder anmelden
editHTML=HTML bearbeiten
showAllTasks=Zeige alle Aufgaben
hideUnimportantTasks=Verstecke unwichtige Aufgaben
filesystem=Dateisystem
papierkorb=Papierkorb
deleteDate=Löschdatum
deletedBy=Gelöscht durch
recycleSubpagesInfo=Beim Wiederherstellen der Seite "$t" würden auch die folgenden Seiten wiederhergestellt werden:
recycleSubpagesInfo1=Beim Wiederherstellen der Seite "$t" würde auch diese Seite wiederhergestellt werden:
Wiederherstellen=Wiederherstellen
EndgueltigLoeschen=Endgültig löschen
recycle.confirm.pop=Wiederherstellen der Seite \'$t\'?
recycle.confirm.pop.subpages=Wiederherstellen der Seite \'$t\' inkl. Unterseiten?
recycle.confirm.delete=Endgültiges Löschen der Seite \'$t\'?
recycle.confirm.delete.subpages=Endgültiges Löschen der Seite \'$t\' inkl. Unterseiten?
PapierkorbLeer=Der Papierkorb ist leer.
ConfirmPapierkorbLeeren=Papierkorb leeren?
PapierkorbLeeren=Papierkorb leeren
titleSearch=Titelsuche
exitPreview=Vorschau beenden
toBooks=zu den Büchern
keepOldInput=Es werden ungespeicherte Eingaben angezeigt.
showComment=Erledigten Kommentar anzeigen
showThread=Erledigten Thread anzeigen
hideComment=Erledigten Kommentar ausblenden
hideThread=Erledigten Thread ausblenden
saveError=Fehler beim Speichern der Seite! Inhalte werden im Browser gespeichert. Melden Sie sich erneut an und beginnen Sie erneut mit der Bearbeitung.
saveCommentError=Fehler beim Speichern des Kommentars! Inhalte werden im Browser gespeichert. Melden Sie sich erneut an und beginnen Sie erneut mit der Bearbeitung.
savedContent=Für diese Seite gibt es noch ungespeicherten Inhalt. Bitte starte die Seitenbearbeitung!
savedCommentContent=Für diesen Kommentar gibt es noch ungespeicherten Inhalt. Bitte starte die Kommentarbearbeitung!
checkAllLinks=Alle Links überprüfen
checkLink=Der Link zu "$h" funktioniert nicht und befindet sich auf der Seite <a href="$v">$t</a> mit dem Linktitel "$l".
hasAbsoluteUrlImage=Seite enthält eine http-Grafik. Bitte korrigieren!
v.hasAbsoluteUrlImage=Seite enthält eine http-Grafik. Bitte korrigieren! $0
enterTitle=Bitte Titel eingeben!
tasksCreatedByMe=Von mir erstellte Aufgaben
tasksCreatedByMeInfo=Hier werden alle von mir erstellte Aufgaben gelistet, die jemand anderem zugewiesen sind und noch nicht erledigt sind.
validation=Validierung
externalLinks=Externe Links
moreTags=weitere tags
colsCustomerRows=Spalten: Kunden, Reihen
bookType=Typ
bookType_PUBLIC=Online-Hilfe
bookType_CUSTOMER=Online-Hilfe (Kunde)
bookType_INTERNAL=internes Buch
bookType_FEATURE_TREE=Featurebaum
keyValues=Schlüsselverwaltung
masks=Masken
addNewMask=Neue Maske anlegen
fields=Felder
deleteMask=Maske löschen
deleteMask1=Maske
deleteMask2=samt aller Daten löschen?
mask=Maske
label=Beschriftung
importField=Importfeld
maskFieldType=Maskenfeldtyp
deleteMaskField=Maskenfeld löschen
deleteMaskField1=Maskenfeld
deleteMaskField2=löschen?
addNewMaskField=Neues Maskenfeld erstellen
maskFieldType_TEXT=Text
maskFieldType_TEXTAREA=Text (mehrzeilig)
maskFieldType_INTEGER=Integer
maskFieldType_BOOL=Bool
maskFieldType_UNIQUE=eindeutig
maskFieldType_CUSTOMERS=Kunden
maskFieldType_USER=Benutzer
up=hoch
down=runter
addMaskField=Neues Maskenfeld anlegen
editMaskField=Maskenfeld bearbeiten
editFeatureFields=Feature-Felder bearbeiten
editFeatureFieldsBtn=Feature-Felder und -Beziehungen bearbeiten
valueIsntUnique=$l Wert "$v" ist nicht eindeutig. Bitte den Wert so ändern, dass dieser nur einmalig vorkommt!
search=Suchen
empty=leer
Responsibilities=Zuständigkeiten
createRelations=Beziehungen erstellen/löschen
relations=Beziehungen
createRelations=Beziehungen erstellen
relationsInfo=Mit welchen Features/Seiten/Webseiten soll dieses Feature verknüpft werden? Bitte jeweils einen Eintrag pro Zeile machen. Es müssen nicht alle Felder gefüllt werden.
zuLoeschendeBeziehungenAnhaken=Beziehungen löschen
Features=Features
vonMirBeobachteteSeiten=Von mir beobachtete Seiten
alleUnterseitenVon=Alle Unterseiten von
watchers=Beobachter
copy-of=Kopie von
copy-n-of=Kopie $n von
duplicatePage=Seite duplizieren
kvtectype=Technischer Schlüsseltyp
kvtypetitle=Schlüsseltyptitel
kvvalues=Schlüsselwerte
kvtype=Schlüsseltyp
kvcreatetype=Neuen Schlüsseltyp anlegen
kvedittype=Schlüsseltyp $t bearbeiten
kvmanagevalues=Schlüsselverwaltung
kverror1=Bitte Typ und Titel eingeben!
kverror2=Bitte Titel eingeben!
kverror3=Technischer Schlüsseltyp bereits vergeben!
kvdeletekeyt=Schlüsseltyp {title} löschen?
kvdeletekey=Schlüsseltyp löschen
sameTitles=Gleiche Titel
erlaeuterungen=Erläuterungen
validationErlaeuterungen=Im Abschnitt "Validierung" sind Fehlermeldungen einiger Seitenprüfungen gelistet. Diese Fehler sollte man korrigieren. "Gleiche Titel" listen gleiche Seitentitel auf. Gleiche Titel sind (technisch) erlaubt und stellen oft keinen Fehler dar. Manchmal kann es aber dennoch unbeabsichtigt passiert sein, dass man zu einem Thema zwei oder mehr Seiten angelegt hat. "Ungenutzte Grafiken" können nicht durch den Anwender korrigiert werden und stören auch nicht weiter. Es ist die Aufgabe von Minerva dies zu bereinigen. "Externe Links": solange ein Link für den Leserkreis erreichbar ist, ist alles gut.
Help=Hilfe
MinervaHelp=Minerva Hilfe
helpKeysErrors=Es gibt Hilfe-Keys für nicht mehr existierende Überschriften:
deleteTheseHelpKeys=Diese Hilfe-Keys löschen!
Filename=Dateiname
Categories=Kategorien
EditCategories=Kategorien bearbeiten
uploadAttachment=Attachment hochladen
deleteAttachment1=Datei "
deleteAttachment2=" löschen?
EditAttachmentCategories=Attachment Kategorien bearbeiten
attachmentDoesnotExist=Attachment nicht vorhanden!
emptyCategories=Bitte geben Sie mindestens eine Kategorie ein!
upload1file=Bitte Dateien einzeln hochladen!
noAttachments=keine Attachments vorhanden
customerMode=Kundenmodus
turnOffCustomerMode=Kundenmodus ausschalten!
customerModeIsOff=Kundenmodus ist aus
exclusionsInfo=Seiten, die eines dieser tags haben, werden nicht angezeigt
exclusionsInfoPlus=Seiten, die eines dieser tags haben, werden angezeigt (zweithöchste Priorität)
exclusionsInfoMinus=Seiten, die eines dieser tags haben, werden auf keinen Fall angezeigt (höchste Priorität)
featureNumbersToJira=Die Featurenummern wurden nach Jira übertragen.
saveFeatures=Speichere Features
iAmResponsible=Ich bin Zuständiger.
QuicklyCreateFeaturesTitle=Schnelles Erstellen von Features
QuicklyCreateFeaturesPageInfo=Bitte pro Zeile ein Feature eingeben. 0 bis n Minus-Zeichen für die Einrückungstiefe voranstellen. Hinter dem Featuretitel kann mit # abgetrennt die Featurenummer angegeben werden.
linkResolverPage1=Unfertige Links ersetzen
linkResolverPage2=Bitte nach einem Seitentitel suchen, damit der Link mit dessen Seiten ID ersetzt werden kann.
linkResolverPage3=nach Seitentitel suchen
linkResolverPage4=Ergebnisliste
linkResolverPage5=Es wurde in der Seite "$p" ein Link mit <br>Adresse <b>"$h"</b> und Titel <b>"$t"</b> gefunden.
qbofftext=Zeige Suchergebnisse für alle Bücher
buchfilter=Buchfilter
crossBookLinksMenu=Verknüpfe Seiten
crossBookLinks=Verknüpfe Seiten aus anderen Büchern
AddPage=Seite hinzufügen
NoLinkedPages=Es wurden bisher keine Seiten verknüpft.
NoPagesToAdd=Es gibt keine Seiten zum Hinzufügen.
