reorder=Reorder
subpages=Subpages
sort=Sort
edit=Edit
newPage=New page
newFeature=New feature
pullT=Reload page from server
none=none
move=Move
delete=Delete
language=Language
alfaSorted=sorted alphabetically
manuSorted=sorted manually
sortConfirm=Save alphabetical sorting of the direct subpages?
pageToPrev=previous page
pageToNext=next page
newBook=New book
title=Title
ordner=Folder
books=Books
pullWS=Update workspace
cloneWS=Reload entire workspace
tagCloud=Tag cloud
orderByName=order by name
orderBySize=order by size
selectWS=Choose workspace. Create a new workspace if you don't see the needed branch.
persistence=Persistence
createWS=Create new workspace
save=Save
cancel=Cancel
deletePage1=You are about to delete the page
deletePage2=The page will be deleted in all languages and with all the images it contains. All subpages, attachments and comments will also be deleted.
deletePage3=The deletion action can be undone via the recycle bin.
deletePage=Delete page
keepPage=Keep page
addBook=Create new book
buchtitel=Book title
editBook=Edit book
deleteBook=Delete book
deleteBook1=This deletes the book entry
deleteBook2=The book folder is not deleted and may need to be manually deleted from the storage system.
keepBook=Keep book
reorderSubpages=Reorder subpages
reorder1=Please rearrange the subpages using drag & drop:
fertigSpeichern=Finished, save it!
linkResolver1=Select page <b>$t</b> and continue...
linkResolver0=Keep link unchanged and continue...
message=Message
goToHomepage=Go to homepage
pageNotFound=This page does not exist.
pageNotFound2=Sorry, the page you are looking for is not available. The information you are looking for may be in a different location or the page no longer exists. Start again from the homepage.
pageNotFound3=Feature or page with ID "$id" does not exist!
linkMustStartWithHttp=Link must start with http:// or https:// !
error.enterFolder=Please enter folder!
error.folderAlreadyExists=Book folder does already exist. Please use another book folder.
error.enterTitle=Please enter title!
error.simultaneousEditing=Simultaneous editing detected!
error.imageTooBig=Please use an image that is not bigger than 10 MB!
createWS1=Already created workspaces and Minerva internal branches are not displayed in the list.
deleteWS=Delete workspace
deleteWS1=This deletes the workspace
deleteWS2=The branch is not deleted from the Gitlab repository.
deleteWS3=Workspace "master" is not allowed to be deleted!
deleteWS4=Last workspace can not be deleted!
keepWS=Keep workspace
Comment=Comment
addComment=Add comment
editComment=Edit comment
answerComment=Reply to comment
comment-by=Comment by
viewTask=View $t
comments=Comments
backToPage=Back to page
reply=Reply
deleteQ=Delete comment?
movePage=Move page
movePage1=Page $t gets page $p as the new parent page.
movePage2=Page "$t" will be moved to book "$b".
deletePage=Delete page
logout=Logout
noBranchForMerge=There are no branches.
noBranchToAdd=A workspace has already been created for each branch.
currentParentPage=current parent page
ParentPage=Parent page
deleteAllTags=Delete all tags
newTag=New tag
anzahl=size
page=Page
book=Book
author=Author
authors=Authors
createdAt=Created
preview=Preview
otherBook=other book
reindex=Update search index
searchPlaceholder=full-text search
volltextsuche=Full-text search
treffer=Search hits
reindex-complete=The search index has been updated for all books.
viewBook=View book in editing area
viewPage=View page in editing area
hasText=text available
hasComment=comment(s) available
exclusions=Exclusions
noSpecificCustomer=no specific customer
addMoreTags=Add tags
noTags=no tags
noComments=no comments
allPages=show all pages
allPagesOff=Show all pages OFF
done=Done
doneComment=set comment as done
undoneComment=set comment as not done
zustaendig=assigned to
doneBy=done
myTasks=My tasks
Tasks=Tasks
history=History
date=Date
newTag=New tag
historyFor=Git history for file
editTags=Edit tags
whatChanged=What did you change?
lastChangeInfo=last change from $d by $u$c
lastChangeInfoForBook=last change of page "<a href="$h">$p</a>" from $d by $u$c
pageLinkToThisPage=The page below links to this page (or subpage(s)). It is recommended to correct the links first so that no broken links are created.
pagesLinkToThisPage=The pages below link to this page (or subpage(s)). It is recommended to correct the links first so that no broken links are created.
helpKeys=Help keys
allHelpKeys=All help keys
updateOnlineHelp=Update online help
session-expired=Session has expired. Please login again.
customerMapping=Mapping
force=force
mapping1=Existing mappings
mapping2=Add mapping
favorite=Favorite
Favorites=Page favorites
linkAnalysis=Link analysis
type=Type
linkTitle=Link title
pageTitle=Page title
formulaEditor=Formulas
formula=formula
giveAdminRights=Admin rights
dropAdminRights=Drop admin rights
serverlog=Server log
createBranch=Create branch
branchName=Branch name
validBranchName=Please enter valid branch name!
createBranchM=Create new branch on branch $m.
mergeBranch=Merge branch
noBranches=There are no branches.
sourceBranch=Source branch
mergeInfo=Merge which branch into branch $m?
Branch=Branch
mergen=Merge
noLinks=no links
export=Export
exportWhat=Export what
customer=Customer
allBooks=all books
booksModeTitle=Books overview
back=back
forward=forward
Forward=Forward
exportTemplates=Export templates
booksOverview=Books overview
template=Template
Menu=Menu
watchPage=Watch page
watchSubpages=Watch subpages
notExistingBranch=The branch no longer exists in the Gitlab repository. Please delete the workspace.
workspaceNotOk=Workspace "$b" is not okay!
ctrlS=Ctrl-S
workspaceHistory=All changes
noMoreCommits=no more commits
locked.header=Page locked
locked.info1=The page "$t" is currently being edited by $u.
locked.info2=The page "$t" is currently being edited by $u. Editing session of user $u will be cancelled. All changes made by user $u will be lost!
locked.smallinfo1=Locked until $o o'clock
locked.edit1=Cancel open session anyway
locked.edit2=Continue anyway
locked.no-edit=OK, don't edit
locked.info1.self=You are already editing the page "$t"!?
locked.smallinfo1.self=You can avoid this lock in the future by clicking "Cancel" to abort the editing. Locked until $o o'clock
locked.edit1.self=Edit page anyway
brokenMappingsInfo=There are no broken mappings.
close=close
TOC=Table of contents
standard=standard
off=off
tocHeadingsLevels=Levels for headings
tocSubpagesLevels=Levels for subpages
cantDeleteAllFiles=Not all files could be deleted!\nPlease contact the administrator. ID $id
editorsNote=Editor's note
clickToRemove=click to hide
mergeRequestCantBeMerged=Merge Request <a href="$url" target="_blank">$id</a> can not be merged. Please <a href="$url/conflicts" target="_blank">resolve the conflicts</a> in Gitlab, commit them and merge the merge request. After that <a href="/w/$tb/pull">refresh</a> the Minerva workspace.
user=User
moveToBookInfo=Links will not work if you move the page to another book.

v._ok=OK. No errors.
v._emptyHTML=Page is empty.
v.noBody=Page has no body tag.
v.illegalHeading=Heading of that level is not allowed. $0
v.firstHeadingMustBe1=Page must start with heading level 1.
v.headingGap=Page contains a gap between heading level $0 and heading level $1.
v.emptyLinesAtBegin=There are $0 empty lines at the begin.
v.emptyLinesAtBegin1=There is $0 empty line at the begin.
v.emptyLinesAtEnd=There are $0 empty lines at the end. 
v.emptyLinesAtEnd1=There is $0 empty line at the end. 
v.doubleEmptyLines=There are $0 double empty lines pairs.
v.doubleEmptyLines1=There is $0 double empty lines pairs.
v.illegalTagsInHeading=Heading must not contain formatting: $0
v.missingImageFile=Missing image file: $0
v.httpImage=Image file with http(s) URL: $0
v.brokenLocalAnchor=The local anchor link "$1" points to the nonexistent heading "$0".
unusedImages=Unused images
validate=Validate pages
nMessages=Number of errors
nPages=Number of pages with errors
openComment=open comment
openComments=open comments
commitMessage=Commit message
beginFSMode=Turn on delayed persistence
endFSMode=Turn off delayed persistence (Save)
endFSModeInfo=Turn off delayed persistence. Should all your changes be persisted or discarded?
persist=Persist
cancelFSMode=Discard
moveNotAllowedForFSMode=Please do not move a page if delayed persistence is active.
loadReleaseNotes=Import release notes
spacekey=Confluence space key
Release=Release
Import=Import
alleNochNichtVorhandenen=all non-existing
selectRelease=Please select a release!
pageDoesntExist=Page with title "$t" does not exist!
generalChanges=General changes
mailAddress=Mail address
exportAllowed=Export allowed
yes=yes
manageUsers=Manage users
editUser=Edit user
addUser=Add user
createUser=Add user
deleteUser=Delete user
deleteUserX=Delete user $user?
multiPageHtml=Multi page HTML
exportFormat=Export format
goToMenu=Go to menu
downloadExportInfo=The export has been created. Please download the file:
export-already-downloaded=The file has already been downloaded and no longer exists. Please run the export again if necessary.
addExportTemplateSet=Add export template set
editExportTemplateSet=Edit export template set
deleteExportTemplateSet=Delete export template set
no-export-template-sets=Export not possible because there are no export template sets!
copy=copy
copyExportTemplateSet=Copy export template set
pdfToc=Cover and TOC
anotherExport=Do another export
moreCommands=More commands
withCover=with cover
withTOC=with table of contents
withChapters=with chapter numbers
exportInfo=If you select "all books", the feature tree and internal books will not be included. If you select customer "-", no tags will be taken into account, i.e. <i>all</i> pages will be exported.
selectPage=Select page(s)
seitenauswahl=Export: select page(s)
pages=Pages
doExport=export
selectPageError=Please select page!
createBookInfo=Please create a book.
exportPage=Export this page
loggedOut=Successfully logged off.
relogin=Log in again
editHTML=Edit HTML
showAllTasks=Show all tasks
hideUnimportantTasks=Hide unimportant tasks
filesystem=file system
papierkorb=Recycle bin
subpages=Subpages
deleteDate=Delete date
deletedBy=Deleted by
recycleSubpagesInfo=Restoring page "$t" would also restore the following pages:
recycleSubpagesInfo1=Restoring page "$t" would also restore this page:
Wiederherstellen=Restore
EndgueltigLoeschen=Delete
recycle.confirm.pop=Restore page \'$t\'?
recycle.confirm.pop.subpages=Restore page \'$t\' and all subpages?
recycle.confirm.delete=Delete page \'$t\'? This can not be undone.
recycle.confirm.delete.subpages=Delete page \'$t\' and all subpages? This can not be undone.
PapierkorbLeer=No entries.
PapierkorbLeeren=Clear recycle bin? This can not be undone.
ConfirmPapierkorbLeeren=Clear recycle bin? This can not be undone.
PapierkorbLeeren=Clear recycle bin
titleSearch=title search
exitPreview=Exit preview
toBooks=to books
keepOldInput=Unsaved input is displayed.
showComment=Show done comment
showThread=Show done thread
hideComment=Hide done comment
hideThread=Hide done thread
saveError=Error saving page! Contents are saved to browser. Log-in again and start editing again.
saveCommentError=Error saving comment! Contents are saved to browser. Log-in again and start editing again.
savedContent=There is unsaved content for this page. Please start editing the page!
savedCommentContent=There is unsaved content for this comment. Please start editing the comment!
checkAllLinks=Check all links
checkLink=Link to "$h" is broken and can be found on page <a href="$v">$t</a> with link label "$l".
hasAbsoluteUrlImage=Page contains a http image! Please fix that!
v.hasAbsoluteUrlImage=Page contains a http image! Please fix that! $0
enterTitle=Please enter title!
tasksCreatedByMe=Tasks created by me
tasksCreatedByMeInfo=All tasks I have created that are assigned to someone else and have not yet been completed are listed here.
validation=Validation
externalLinks=External links
moreTags=more tags
colsCustomerRows=Columns: customers, rows
bookType=Type
bookType_PUBLIC=Online help
bookType_CUSTOMER=Online help (customer)
bookType_INTERNAL=Internal book
bookType_FEATURE_TREE=Feature tree
keyValues=Key Values
masks=Masks
addNewMask=Create new mask
fields=Fields
deleteMask=Delete mask
deleteMask1=Delete mask
deleteMask2=with all data?
mask=Mask
label=Label
importField=Import field
maskFieldType=Mask field type
deleteMaskField=Delete mask field
deleteMaskField1=Delete mask field
deleteMaskField2=?
addNewMaskField=Create new mask field
maskFieldType_TEXT=Text
maskFieldType_TEXTAREA=Text (multi-line)
maskFieldType_INTEGER=Integer
maskFieldType_BOOL=Bool
maskFieldType_UNIQUE=unique
maskFieldType_CUSTOMERS=Customers
maskFieldType_USER=User
up=up
down=down
addMaskField=Create new mask field
editMaskField=Edit mask field
editFeatureFields=Edit feature fields
valueIsntUnique=$l value "$v" isn't unique. Please change value!
search=Search
empty=empty
Responsibilities=Responsibilities
createRelations=Create/delete relation
relations=Relations
zuLoeschendeBeziehungenAnhaken=Please tick relations to be deleted
Features=Features
vonMirBeobachteteSeiten=Pages watched by me
alleUnterseitenVon=All subpages of
watchers=Watchers
copy-of=Copy of
copy-n-of=Copy $n of
duplicatePage=Duplicate page
kvtectype=Techncal key type
kvtypetitle=Key type title
kvvalues=Values
kvtype=Key type
kvcreatetype=Create new key type
kvedittype=Edit key type: $t
kvmanagevalues=Manage key values
kverror1=Please enter type and title!
kverror2=Please enter title!
kverror3=Technical key type already in use!
kvdeletekeyt=Delete key type {title}?
kvdeletekey=Delete key type
sameTitles=Same titles
erlaeuterungen=Explanations
validationErlaeuterungen=The "Validation" section lists error messages from some page checks. These errors should be corrected. "Same titles" list identical page titles. Identical titles are (technically) permitted and often do not constitute an error. Sometimes, however, it can happen unintentionally that two or more pages have been created on one topic. "Unused graphics" cannot be corrected by the user and do not cause any further problems. It is Minerva's job to clean this up. "External links": as long as a link is accessible to the readership, everything is fine.
Help=Help
MinervaHelp=Minerva Help
helpKeysErrors=There are help keys for headings that no longer exist:
deleteTheseHelpKeys=Delete these help keys!
Filename=Filename
Categories=Categories
EditCategories=Edit categories
uploadAttachment=Upload attachment
deleteAttachment1=Delete attachment "
deleteAttachment2="?
EditAttachmentCategories=Edit attachment categories
attachmentDoesnotExist=Attachment does not exist!
emptyCategories=Please enter at least one category!
upload1file=Please upload files individually!
noAttachments=no attachments
reimportReleaseNotes=Import release notes again?
ErneutImportieren=Re-import
pageOnly1HelpKey=Page must have exactly one help key!
helpKeyMustBeReleaseNumber=The help key must be a valid release number!
cantGetCustomer=Can't get customer! Parent customer page has no tag 'release-notes-...'.
unknownCustomerCode=Customer code unknown! The parent customer page must have a tag 'release-notes-' + valid customer code!
multipleTargetVersion='Target release version' $rn appears multiple times in Jira release tickets!
noReleaseTicket=There is no release ticket for customer $c and 'Target release version' $rn !
reimportFailed1=Re-import failed. No release note tickets were found using page ID "$p".
