reorder=Reorder
subpages=Subpages
sort=Sort
edit=Edit
newPage=New page
pullT=Reload page from server
none=none
move=Move
delete=Delete
language=Language
alfaSorted=sorted alphabetically
manuSorted=sorted manually
sortConfirm=Hiermit speichern Sie eine alphabetische Sortierung der direkten Unterseiten!
pageToPrev=previous page
pageToNext=next page
newBook=New book
title=Title
ordner=Folder
books=Books
pullWS=Update workspace
cloneWS=Reload entire workspace
tagCloud=Tag cloud
orderByName=order by name
orderBySize=order by size
selectWS=Choose workspace. Create a new workspace if you don't see the needed branch.
persistence=Persistence
createWS=Create new workspace
save=Save
cancel=Cancel
deletePage1=You are about to delete the page
deletePage2=The page will be deleted in all languages and with all the images it contains. All subpages will also be deleted.
deletePage=Delete page
keepPage=Keep page
addBook=Create new book
buchtitel=Book title
editBook=Edit book
deleteBook=Delete book
deleteBook1=This deletes the book entry
deleteBook2=The book folder is not deleted and may need to be manually deleted from the storage system.
keepBook=Keep book
reorderSubpages=Reorder subpages
reorder1=Please rearrange the subpages using drag & drop:
fertigSpeichern=Finished, save it!
linkResolver1=Select page <b>$t</b> and continue...
linkResolver0=Keep link unchanged and continue...
message=Message
goToHomepage=Go to homepage
pageNotFound=This page does not exist.
pageNotFound2=Sorry, the page you are looking for is not available. The information you are looking for may be in a different location or the page no longer exists. Start again from the homepage.
error.enterFolder=Please enter folder!
error.folderAlreadyExists=Book folder does already exist. Please use another book folder.
error.enterTitle=Please enter title!
error.simultaneousEditing=Simultaneous editing detected! Please go back, save the changes, reload the page and redo the edit.
error.imageTooBig=Please use an image that is not bigger than 10 MB!
createWS1=Already created workspaces and Minerva internal branches are not displayed in the list.
deleteWS=Delete workspace
deleteWS1=This deletes the workspace
deleteWS2=The branch is not deleted from the Gitlab repository.
deleteWS3=Workspace "master" is not allowed to be deleted!
deleteWS4=Last workspace can not be deleted!
keepWS=Keep workspace
note=Comment
addNote=Add comment
editNote=Edit comment
viewNote=View comment
notes=Comments
backToPage=Back to page
reply=Reply
deleteQ=Delete comment?
movePage=Move page
movePage1=Page $t gets page $p as the new parent page.
movePage2=Page "$t" will be moved to book "$b".
deletePage=Delete page
logout=Logout
noBranches=A workspace has already been created for each branch.
currentParentPage=current parent page
deleteAllTags=Delete all tags
newTag=New tag
anzahl=size
page=Page
book=Book
allNotes=All comments
author=Author
authors=Authors
createdAt=Created
preview=Preview
otherBook=other book
reindex=Update search index
searchPlaceholder=full-text search
volltextsuche=Full-text search
treffer=Search hits
reindex-complete=The search index has been updated for all books.
viewBook=View book in editing area
viewPage=View page in editing area
hasNote=comment(s) available
exclusions=Exclusions
noSpecificCustomer=no specific customer
addMoreTags=Add tags
noTags=no tags
noNotes=no comments
allPages=Show all pages
done=Done
doneNote=set comment as done
undoneNote=set comment as not done
zustaendig=assigned to
doneBy=done by
myTasks=My tasks
history=History
date=Date
newTag=New tag
historyFor=Git history for file
editTags=Edit tags
whatChanged=What did you change?
lastChangeInfo=last change from $d by $u$c
lastChangeInfoForBook=last change of page "<a href="$h">$p</a>" from $d by $u$c
pageLinkToThisPage=This page links to this page. It is recommended to correct the links first so that no broken links are created.
pagesLinkToThisPage=These pages link to this page. It is recommended to correct the links first so that no broken links are created.
helpKeys=Help keys
allHelpKeys=All help keys
updateOnlineHelp=Update online help
session-expired=Session has expired. Please login again.
customerMapping=Mapping
force=force
mapping1=Existing mappings
mapping2=Add mapping
favorite=Favorite
linkAnalysis=Link analysis
type=Type
linkTitle=Link title
pageTitle=Page title
formulaEditor=Formulas
formula=formula
giveAdminRights=Admin rights
dropAdminRights=Drop admin rights
serverlog=Server log
createBranch=Create branch
branchName=Branch name
validBranchName=Please enter valid branch name!
createBranchM=Create new branch on branch $m.
mergeBranch=Merge branch
noBranches=There are no branches.
sourceBranch=Source branch
mergeInfo=Merge which branch into branch $m?
Branch=Branch
mergen=Merge
noLinks=no links
export=Export
exportWhat=Export what
customer=Customer
allBooks=all books
exportInfo=Books or pages are exported as multi-page HTML files and downloaded as a zip file.
booksModeTitle=Books overview
back=back
forward=forward
exportTemplates=Export templates
booksOverview=Books overview
template=Template
Menu=Menu
watchPage=Watch page
watchSubpages=Watch subpages
notExistingBranch=The branch no longer exists in the Gitlab repository. Please delete the workspace.
workspaceNotOk=Workspace "$b" is not okay!
ctrlS=Ctrl-S
workspaceHistory=All changes
noMoreCommits=no more commits
locked.header=Page locked
locked.info=The page "$t" is currently being edited by $u.
locked.time=Locked until $o o'clock
locked.edit=Edit page anyway
locked.no-edit=OK, don't edit
brokenMappingsInfo=There are no broken mappings.
close=close
TOC=TOC
standard=standard
off=off
tocHeadingsLevels=Levels for headings
tocSubpagesLevels=Levels for subpages
cantDeleteAllFiles=Not all files could be deleted!\nPlease contact the administrator. ID $id
editorsNote=Editor's note
clickToRemove=click to hide
mergeRequestCantBeMerged=Merge Request <a href="$url" target="_blank">$id</a> can not be merged. Please <a href="$url/conflicts" target="_blank">resolve the conflicts</a> in Gitlab, commit them and merge the merge request. After that <a href="/w/$tb/pull">refresh</a> the Minerva workspace.
user=User
moveToBookInfo=Links will not work if you move the page to another book.
noWS4branch=Workspace does not exist for branch "$b"! Please create workspace on Workspaces page and try again.

v._ok=OK. No errors.
v._emptyHTML=Page is empty.
v.noBody=Page has no body tag.
v.illegalHeading=Heading of that level is not allowed. $0
v.firstHeadingMustBe1=Page must start with heading level 1.
v.headingGap=Page contains a gap between heading level $0 and heading level $1.
v.emptyLinesAtBegin=There are $0 empty lines at the begin.
v.emptyLinesAtBegin1=There is $0 empty line at the begin.
v.emptyLinesAtEnd=There are $0 empty lines at the end. 
v.emptyLinesAtEnd1=There is $0 empty line at the end. 
v.doubleEmptyLines=There are $0 double empty lines pairs.
v.doubleEmptyLines1=There is $0 double empty lines pairs.
v.illegalTagsInHeading=Heading must not contain formatting: $0
validate=Validate pages
nMessages=Number of errors
nPages=Number of pages with errors
openNote=open comment
openNotes=open comments
